version: "3"

services:
  nextjs-dev:
    build:
      context: .
      dockerfile: dockerfile
      target: deps
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
