import type { Metadata } from "next";
import { Lato } from "next/font/google";
import { Footer } from "@/components/shared/Footer";
import { Header } from "@/components/shared/header/Header";
import { LoginForm } from "@/components/auth/login/LoginForm";
import { Sidebar } from "@/components/shared/sidebar/Sidebar";
import "./globals.css";

const lato = Lato({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} font-sans antialiased flex space-between flex-col min-h-screen overflow-x-hidden`}
      >
        <Header />
        <Sidebar />
        <LoginForm />
        {children}
        <Footer />
      </body>
    </html>
  );
}
